#!/usr/bin/env python3
"""Generate the bundled JS and native LuCI catalogues from the Chinese PO file."""
import argparse
import hashlib
import json
import pathlib
import re
import shutil
import subprocess

ROOT = pathlib.Path(__file__).resolve().parents[1]
PO = ROOT / "po/zh_Hans/device-manager.po"
JS = ROOT / "htdocs/luci-static/resources/device-manager/translations.js"
LMO = ROOT / "root/usr/lib/lua/luci/i18n/device-manager-builtin.zh-cn.lmo"


def messages():
    entries = {}
    for block in PO.read_text().split("\n\n"):
        key = re.search(r'^msgid (".*")$', block, re.M)
        value = re.search(r'^msgstr (".*")$', block, re.M)
        if key and value and json.loads(key[1]):
            text = json.loads(value[1])
            if not text:
                raise ValueError(f"Missing translation: {key[1]}")
            entries[json.loads(key[1])] = text
    return entries


def source():
    digest = hashlib.sha256(LMO.read_bytes()).hexdigest()
    return ("'use strict';\n'require baseclass';\n\n"
            "// Generated by tools/update-translations.py from po/zh_Hans/device-manager.po.\n"
            f"// Native catalogue SHA256: {digest}\n"
            "return baseclass.extend({ messages: " + json.dumps(messages(), ensure_ascii=False, indent="\t") + " });\n")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--po2lmo", default=shutil.which("po2lmo"))
    args = parser.parse_args()
    if args.check:
        if not JS.exists() or not LMO.exists() or JS.read_text() != source():
            parser.error("Bundled translations are stale; regenerate with po2lmo")
    else:
        if not args.po2lmo:
            parser.error("po2lmo is required; supply --po2lmo /path/to/po2lmo")
        LMO.parent.mkdir(parents=True, exist_ok=True)
        subprocess.run([args.po2lmo, str(PO), str(LMO)], check=True)
        JS.write_text(source())
